import Head from 'next/head'
import Home_profile from '../Components/Home_profile'

export default function Home() {
  return (
    <>
      <Head>
        <title>Influencer Destination</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css' />
      </Head>

      <Home_profile />

    </>

  )
}
